[build]
  command = "npx ng build --configuration production"
  publish = "dist/vision-corporation-website/browser"
  trailingSlash = false

[[plugins]]
  package = "@netlify/angular-runtime"

[[edge_functions]]
  function = "angular-ssr"
  path = "/*"

[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 200
  force = true
